"use strict";
(function (root, factory) {
  if (typeof module === "object" && module.exports) {
    module.exports = factory();
  } else {
    root.AkiyaEngine = factory();
  }
})(typeof globalThis !== "undefined" ? globalThis : typeof self !== "undefined" ? self : this, function () {
/* ---------- 乱数（再現可能） ---------- */
function mulberry32(a){return function(){a|=0;a=a+0x6D2B79F5|0;
  let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;
  return((t^t>>>14)>>>0)/4294967296}}

/* ---------- 定数 ---------- */
const W=84,H=26,N=W*H;
/* 地域（西→東）: 係数は様式化した実勢。実データ差替え対象
   price:価格水準 inc:所得指数 mig:年純流入率 ageS:所有者年齢シフト */
const ZONES=[
 {n:"西多摩", price:0.40,inc:0.82,mig:0.003368,ageS:+6}, /* mig: data/zones_mig.csv 令和6年 */
 {n:"多摩中部",price:0.58,inc:0.95,mig:0.004930,ageS:+3},
 {n:"多摩東部",price:0.78,inc:1.05,mig:0.003882,ageS:+1},
 {n:"区部西", price:0.98,inc:1.10,mig:0.005499,ageS:0},
 {n:"都心",   price:1.32,inc:1.30,mig:0.004810,ageS:-2},
 {n:"城東",   price:0.82,inc:0.96,mig:0.006160,ageS:-1}];
/* ZONE_GRID_BEGIN — generated by scripts/build_zone_grid.py; do not edit */
const zone=(typeof ZONE_GRID!=="undefined"?ZONE_GRID:(()=>{throw new Error("Load data/zone_grid.gen.js before engine.js")})());
const AFFINE=(typeof ZONE_GRID_META!=="undefined"&&ZONE_GRID_META.affine)?ZONE_GRID_META.affine:{lon0:138.95,lon1:139.93,latN:35.82,latS:35.53};
/* ZONE_GRID_END */
const S_OCC=0,S_RENT=1,S_SALE=2,S_LIST=3,S_NEG=4,S_DEMO=5;
const COLORS=["#aeb9be","#8fa8a0","#d9a441","#d9a441","#c04a2a","#e6e2d8"];
const STATIONS=[[36,13],[52,12],[63,13],[74,12]]; // 立川・吉祥寺・新宿・東京駅相当
const P={ // v0.4 — ストック更新 + 相続分岐ナラティブ
  demoBase:220, landFrac:0.21, txCost:0.06, rentYield:0.045, horizon:10,
  renovCost:150, holdCost:8, taxRelief:8,   // 万円 / 年（特例による軽減分＝解体で失う）
  vacDecay:0.03, priceVacElast:1.2, deathK:0.085, deathMid:86,
  moveOut:0.0075, tenantLeave:0.052, upkeep:9, liqPref:0.10,
  effort:38, hassle:25, choiceNoise:18,
  // 非経済: 社会的規範・家計余裕不足・区切り解体
  normK:24, poorBar:42, closureK:4.5,
  // 補助（様式化）。政策経路は後追いだが既存つまみは維持
  subEff:0.62, subClosure:0.80, subEaseMax:0.65, demoAttach:0.08, subCostCap:0.42,
  // 相続分岐: 市場性が高いほど即売却/賃貸、低い・遠隔・共有ほど放置へ
  inheritSell:0.40, inheritList:0.32, inheritNegBase:0.22,
  // 転出: 必ずしも放置せず、売出・募集にも分岐
  moveSell:0.40, moveList:0.40, moveNeg:0.20,
  // ストック更新: 更地→再利用（需要×価格が高いほど速い）
  rebuildBase:0.085, rebuildMig:18, rebuildPrice:0.35,
  // 建替圧力: 老朽居住の一部が一旦更地化され再建される（ごく少数）
  rebuildOcc:0.0015,
};

/** 家計余裕の代理: 立地×品質×地域所得（西多摩〜都心で 0.3〜2 程度） */
function ownerWealth(w,i){
  const Z=ZONES[zone[i]];
  return w.loc[i]*w.q[i]*Z.inc;
}

/** 相続直後の処分分岐。
 * ナラティブ: 市場性が高いほど即売却/賃貸しやすいが、
 * 東京は空き家率が地域横断で平坦〜なので分岐を極端にしない。
 * 遠隔・共有名義が放置経路の本丸。
 */
function inheritDisposition(w,i,r){
  const Z=ZONES[zone[i]];
  const friction=0.70*w.oRemote[i]+0.30*(w.oCo[i]-1);
  // 東京の空き家率は地域でほぼ平坦 → 市場性より摩擦（遠隔・共有）で分岐
  let pSell=0.40-0.18*friction;
  let pList=0.34-0.08*friction;
  let pNeg=0.16+0.32*friction;
  pSell=Math.max(0.22,Math.min(0.55,pSell));
  pList=Math.max(0.22,Math.min(0.48,pList));
  pNeg=Math.max(0.10,Math.min(0.50,pNeg));
  const s=pSell+pList+pNeg;
  const u=r()*s;
  if(u<pSell) return S_SALE;
  if(u<pSell+pList) return S_LIST;
  return S_NEG;
}

function resetOwnerAfterMatch(w,i,r,asOwner){
  if(asOwner){
    w.oAge[i]=32+18*r();
    w.oRemote[i]=0;
    w.oCo[i]=1;
    w.attach[i]=5+8*r();
  }
  w.negYears[i]=0;
}

/* ---------- ワールド生成 ---------- */
function makeWorld(seed,policy){
  const rng=mulberry32(seed);
  const loc=new Float32Array(N), q=new Float32Array(N), st=new Uint8Array(N);
  const oAge=new Float32Array(N), oRemote=new Uint8Array(N), oCo=new Uint8Array(N);
  const ZV=(typeof ZONES_VAC!=="undefined"?ZONES_VAC:{rates:ZONES.map(()=>0.109),negFrac:ZONES.map(()=>0.45),saleFrac:ZONES.map(()=>0.15),listFrac:ZONES.map(()=>0.35)});
  const byZone=ZONES.map(()=>[]);
  for(let i=0;i<N;i++) if(zone[i]>=0) byZone[zone[i]].push(i);
  function shuffle(a){
    for(let k=a.length-1;k>0;k--){const j=(rng()* (k+1))|0; const t=a[k]; a[k]=a[j]; a[j]=t;}
  }
  for(let z=0;z<ZONES.length;z++){
    const idx=byZone[z]; shuffle(idx);
    const nVac=Math.round((ZV.rates[z]||0.109)*idx.length);
    const nNeg=Math.min(nVac, Math.round((ZV.negFrac[z]||0.45)*nVac));
    const nSale=Math.min(nVac-nNeg, Math.round((ZV.saleFrac[z]||0.15)*nVac));
    const nList=Math.max(0, Math.min(nVac-nNeg-nSale, Math.round((ZV.listFrac[z]||0.35)*nVac)));
    for(let k=0;k<idx.length;k++){
      const i=idx[k];
      const Z=ZONES[z];
      let d=1e9; for(const[sx,sy]of STATIONS){const dx=(i%W)-sx,dy=(i/W|0)-sy;d=Math.min(d,Math.hypot(dx,dy));}
      const stBonus=Math.max(0,0.28-0.045*d);
      loc[i]=Z.price*(0.85+0.30*rng())+stBonus;
      q[i]=0.45+0.5*rng();
      oAge[i]=35+45*rng()+Z.ageS;
      oRemote[i]=rng()<0.12?1:0; oCo[i]=1;
      if(k<nNeg){
        st[i]=S_NEG;
      }else if(k<nNeg+nSale){
        st[i]=S_SALE;
      }else if(k<nNeg+nSale+nList){
        st[i]=S_LIST;
      }else if(k<nVac){
        st[i]=S_LIST;
      }else{
        st[i]=rng()<0.88?S_OCC:S_RENT;
      }
    }
  }
  for(let i=0;i<N;i++) if(zone[i]<0) st[i]=S_DEMO;
  const attach=new Float32Array(N); for(let i=0;i<N;i++)attach[i]=5+8*rng();
  return{seed,policy,rng,loc,q,st,oAge,oRemote,oCo,attach,year:0,
    negYears:new Float32Array(N), hist:{vac:[],neg:[],clu:[],demo:[]}};
}

/* ---------- 近傍空き家率 ---------- */
function neighborVac(w){
  const nv=new Float32Array(N), vac=i=>w.st[i]>=S_SALE&&w.st[i]<=S_NEG;
  for(let y=0;y<H;y++)for(let x=0;x<W;x++){
    let c=0,v=0;
    for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){
      if(!dx&&!dy)continue;
      const nx=x+dx,ny=y+dy;
      if(nx<0||ny<0||nx>=W||ny>=H)continue;
      const j=ny*W+nx; if(zone[j]<0||w.st[j]===S_DEMO)continue;
      c++; if(vac(j))v++;
    }
    nv[y*W+x]=c?v/c:0;
  }
  return nv;
}

/* ---------- 1年進める ---------- */
function step(w){
  const r=w.rng, pol=w.policy, nv=neighborVac(w);
  const price=i=>1800*w.loc[i]*w.q[i]*Math.max(0.35,1-P.priceVacElast*nv[i]); // 万円
  // 成約見込み（年あたり）：立地×品質が高く、近隣空き家が少ないほど埋まりやすい
  const zDem=ZONES.map(Z=>Math.min(1.15,Math.max(0.92,1+6*Z.mig+0.10*(Z.inc-1))));
  // 成約: 立地差を抑えつつ、低価格帯でも最低限の流動性（住調の平坦さを再現）
  const match=i=>{
    const Z=ZONES[zone[i]];
    const base=0.34+0.30*w.loc[i]*w.q[i]-0.12*nv[i]+0.05*(1-Z.price);
    return Math.min(0.68,Math.max(0.20, base*zDem[zone[i]]));
  };

  for(let i=0;i<N;i++){
    if(zone[i]<0)continue;

    // ---- ストック更新: 更地の再利用（需要の高い地域ほど早い）----
    if(w.st[i]===S_DEMO){
      const Z=ZONES[zone[i]];
      const pRebuild=Math.min(0.35, P.rebuildBase
        *(1+P.rebuildMig*Z.mig)
        *(0.55+P.rebuildPrice*Z.price)
        *(1-0.35*nv[i]));
      if(r()<pRebuild){
        // 建替・再入居: 品質をリセットして居住/賃貸へ
        w.q[i]=0.70+0.25*r();
        resetOwnerAfterMatch(w,i,r,true);
        w.st[i]=r()<0.72?S_OCC:S_RENT;
      }
      continue; // 更地セルは所有者加齢フロー対象外
    }

    // 所有者の加齢・死亡 → 相続（分岐付き）
    w.oAge[i]+=1;
    const pDeath=1/(1+Math.exp(-P.deathK*(w.oAge[i]-P.deathMid)));
    if(r()<pDeath){
      w.oAge[i]=Math.max(38,w.oAge[i]-31+8*(r()-0.5));
      w.oRemote[i]=r()<0.40?1:0;
      const u=r(); w.oCo[i]=u<0.5?1:(u<0.82?2:3);
      // 相続直後の愛着は二極: すぐ手放す層は低い、実家保留は高い
      if(w.st[i]===S_OCC||w.st[i]===S_RENT){
        const next=inheritDisposition(w,i,r);
        w.attach[i]=next===S_NEG?(35+50*r()):(4+10*r());
        w.negYears[i]=0;
        w.st[i]=next;
      }else{
        w.attach[i]=20+40*r();
      }
    }

    // 投資・二次的住宅の代理（都心寄りの一時的募集）
    if(w.st[i]===S_OCC){
      const Z=ZONES[zone[i]];
      const pInvest=0.0035+0.012*Math.max(0,Z.price-0.75);
      if(r()<pInvest){ w.st[i]=S_LIST; w.negYears[i]=0; }
    }

    // 転出: 放置一択ではなく売出/募集にも分岐
    if(w.st[i]===S_OCC&&r()<P.moveOut*Math.min(1.15,Math.max(0.55,1-18*ZONES[zone[i]].mig))){
      const Z=ZONES[zone[i]];
      const mkt=0.75+0.35*Z.price;
      let ps=P.moveSell*mkt, pl=P.moveList*mkt, pn=P.moveNeg*(1.15-0.25*Z.price);
      const s=ps+pl+pn; const u=r()*s;
      w.negYears[i]=0;
      if(u<ps) w.st[i]=S_SALE;
      else if(u<ps+pl) w.st[i]=S_LIST;
      else w.st[i]=S_NEG;
    }
    if(w.st[i]===S_RENT&&r()<P.tenantLeave){
      // 退去後: 家主がすぐ再募集する確率が高い
      w.st[i]=r()<0.78?S_LIST:S_NEG;
      if(w.st[i]===S_NEG) w.negYears[i]=0;
    }

    // ごく少数の建替圧力（老朽居住 → 更地経由で更新されるストックの代理）
    if((w.st[i]===S_OCC||w.st[i]===S_RENT)&&w.q[i]<0.35&&r()<P.rebuildOcc*(1.2-w.q[i])){
      w.st[i]=S_DEMO; w.negYears[i]=0;
      continue;
    }

    // 空き家所有者の意思決定（共有名義・遠隔居住は意思決定頻度を下げる）
    if(w.st[i]>=S_SALE&&w.st[i]<=S_NEG){
      w.q[i]=Math.max(0.05,w.q[i]-(w.st[i]===S_NEG?P.vacDecay:P.vacDecay*0.4));
      w.negYears[i]+=(w.st[i]===S_NEG)?1:0;
      const pDecideBase=Math.min(0.95,(1/w.oCo[i])*(w.oRemote[i]?0.55:1)*(1+0.25*pol.tax)
        *(w.st[i]===S_NEG&&w.negYears[i]>=3?1.15:1));
      const wealth=ownerWealth(w,i);
      const slack=Math.min(1.35,Math.max(0.32,wealth));
      const neglectVis=w.st[i]===S_NEG&&w.negYears[i]>=2
        ?0.4+0.07*Math.min(w.negYears[i],22):0;
      const normCost=P.normK*Math.max(0,wealth-0.42)*neglectVis;
      const normPush=w.st[i]===S_NEG&&w.negYears[i]>=2
        ?0.05*Math.max(0,wealth-0.5):0;
      const pDecide=Math.min(0.95,pDecideBase*(1+normPush));
      if(r()<pDecide){
        const pv=price(i), m=match(i);
        const holdTax=(P.holdCost+pol.tax/100*pv)*P.horizon;
        const fade=Math.max(0.25,1-0.05*w.negYears[i]);
        const uNeg=-holdTax-pv*P.vacDecay*P.horizon*0.5+w.attach[i]*fade-normCost;
        const eff=P.effort*w.oCo[i]*(w.oRemote[i]?1.5:1)*Math.max(0.25,1-0.07*w.negYears[i]);
        const poorBar=P.poorBar*Math.max(0,1-slack/0.95);
        const cashStress=poorBar;
        const uSell=m*(holdTax+P.liqPref*pv)-P.hassle-eff;
        const uRent=m*(P.rentYield*pv-P.upkeep)*P.horizon
                    -P.renovCost*(1-w.q[i])*2.0-eff-cashStress*1.6;
        const demoCost = P.demoBase * (0.7 + 0.3 * ZONES[zone[i]].price);
        const landVal = pv * P.landFrac * (0.8 + 0.35 * (1 - ZONES[zone[i]].price));
        const decayY=Math.max(0,w.negYears[i]-14);
        const structuralClosure=decayY*9
          *(0.45+0.55*w.oRemote[i]+0.2*(w.oCo[i]>1?1:0));
        const closureRelief=P.closureK*Math.min(w.negYears[i],22)
          *(0.35+0.6*w.oRemote[i]+0.25*(w.oCo[i]>1?1:0))
          +(w.negYears[i]>=12?18*(0.25+0.75*w.oRemote[i]):0)
          +structuralClosure;
        const subCredit=pol.sub>0
          ?Math.min(demoCost*P.subCostCap, pol.sub*P.subEff):0;
        const subEase=pol.sub>0?Math.min(P.subEaseMax,pol.sub/220)*cashStress*0.9:0;
        const demoCash=cashStress*(w.negYears[i]>=15?0.85:2.4);
        const closureAdj=pol.sub>0?P.subClosure:1;
        const uDemo = landVal + holdTax * (pol.tax > 0 ? 0.75 : 0.6) - (demoCost - subCredit)
                    - P.taxRelief * P.horizon - eff - demoCash + subEase
                    + closureRelief*closureAdj - w.attach[i]*P.demoAttach;
        const us = w.st[i] === S_NEG && w.negYears[i] < 4
          ? [["sale", uSell], ["rent", uRent], ["neg", uNeg]]
          : [["sale", uSell], ["rent", uRent], ["demo", uDemo], ["neg", uNeg]];
        let best=null,bv=-1e18;
        for(const[k,v]of us){const vv=v+P.choiceNoise*(r()-0.5)*2;if(vv>bv){bv=vv;best=k;}}
        if(best==="sale")w.st[i]=S_SALE;
        else if(best==="rent")w.st[i]=S_LIST;
        else if(best==="demo")w.st[i]=S_DEMO;
        else w.st[i]=S_NEG;
      }
    }
  }

  // マッチング：売出・募集中の各物件が成約見込みに応じて埋まる
  for(let i=0;i<N;i++){
    if(zone[i]<0)continue;
    if(w.st[i]===S_SALE||w.st[i]===S_LIST){
      if(r()<match(i)){
        if(w.st[i]===S_SALE){
          w.st[i]=S_OCC; w.q[i]=Math.min(1,w.q[i]+0.15);
          resetOwnerAfterMatch(w,i,r,true);
        }else{
          w.st[i]=S_RENT; w.q[i]=Math.min(1,w.q[i]+0.08);
          w.negYears[i]=0;
        }
      }
    }
  }

  // 集計（更地の再利用が入るので分母は常に有効セル）
  let occ=0,vac=0,neg=0,demo=0,tot=0;
  for(let i=0;i<N;i++){if(zone[i]<0)continue;tot++;
    if(w.st[i]===S_DEMO){demo++;continue;}
    if(w.st[i]>=S_SALE&&w.st[i]<=S_NEG){vac++;if(w.st[i]===S_NEG)neg++;}else occ++;}
  const nv2=neighborVac(w);
  let s=0,c=0;for(let i=0;i<N;i++)if(zone[i]>=0&&w.st[i]>=S_SALE&&w.st[i]<=S_NEG){s+=nv2[i];c++;}
  const clu=(c&&vac/tot>0)?(s/c)/(vac/tot):0;
  // 空き家率分母は「建物あり」（更地除外）— 住調定義に合わせる
  const stock=tot-demo;
  w.hist.vac.push(stock?vac/stock:0);w.hist.neg.push(stock?neg/stock:0);w.hist.clu.push(clu);
  w.hist.demo=(w.hist.demo||[]);w.hist.demo.push(demo/tot);
  w.year++;
}

  return {
    mulberry32, makeWorld, neighborVac, step, ownerWealth, inheritDisposition,
    W, H, N, ZONES, zone, AFFINE,
    S_OCC, S_RENT, S_SALE, S_LIST, S_NEG, S_DEMO,
    COLORS, STATIONS, P,
  };
});
