"use strict";
(function (root, factory) {
  if (typeof module === "object" && module.exports) {
    module.exports = factory();
  } else {
    root.AkiyaEngine = factory();
  }
})(typeof globalThis !== "undefined" ? globalThis : typeof self !== "undefined" ? self : this, function () {
/* ---------- 乱数（再現可能） ---------- */
function mulberry32(a){return function(){a|=0;a=a+0x6D2B79F5|0;
  let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;
  return((t^t>>>14)>>>0)/4294967296}}

/* ---------- 定数 ---------- */
const W=84,H=26,N=W*H;
/* 地域（西→東）: 係数は様式化した実勢。実データ差替え対象
   price:価格水準 inc:所得指数 mig:年純流入率 ageS:所有者年齢シフト */
const ZONES=[
 {n:"西多摩", price:0.40,inc:0.82,mig:0.003368,ageS:+12}, /* mig: data/zones_mig.csv 令和6年 */
 {n:"多摩中部",price:0.58,inc:0.95,mig:0.004930,ageS:+5},
 {n:"多摩東部",price:0.78,inc:1.05,mig:0.003882,ageS:+2},
 {n:"区部西", price:0.98,inc:1.10,mig:0.005499,ageS:0},
 {n:"都心",   price:1.32,inc:1.30,mig:0.004810,ageS:-6},
 {n:"城東",   price:0.82,inc:0.96,mig:0.006160,ageS:-2}];
/* ZONE_GRID_BEGIN — generated by scripts/build_zone_grid.py; do not edit */
const zone=(typeof ZONE_GRID!=="undefined"?ZONE_GRID:(()=>{throw new Error("Load data/zone_grid.gen.js before engine.js")})());
/* ZONE_GRID_END */
const S_OCC=0,S_RENT=1,S_SALE=2,S_LIST=3,S_NEG=4,S_DEMO=5;
const COLORS=["#aeb9be","#8fa8a0","#d9a441","#d9a441","#c04a2a","#e6e2d8"];
const STATIONS=[[36,13],[52,12],[63,13],[74,12]]; // 立川・吉祥寺・新宿・東京駅相当
const P={ // モデルパラメータ（後で実データキャリブレーション対象）
  demoBase:250, landFrac:0.18, txCost:0.06, rentYield:0.045, horizon:10,
  renovCost:150, holdCost:10, taxRelief:8,   // 万円 / 年（特例による軽減分＝解体で失う）
  vacDecay:0.03, priceVacElast:1.2, deathK:0.09, deathMid:84,
  moveOut:0.010, tenantLeave:0.065, upkeep:9, liqPref:0.10,
  effort:38, hassle:25, choiceNoise:18
};

/* ---------- ワールド生成 ---------- */
function makeWorld(seed,policy){
  const rng=mulberry32(seed);
  const loc=new Float32Array(N), q=new Float32Array(N), st=new Uint8Array(N);
  const oAge=new Float32Array(N), oRemote=new Uint8Array(N), oCo=new Uint8Array(N);
  const ZV=(typeof ZONES_VAC!=="undefined"?ZONES_VAC:{rates:ZONES.map(()=>0.109),negFrac:ZONES.map(()=>0.45)});
  const byZone=ZONES.map(()=>[]);
  for(let i=0;i<N;i++) if(zone[i]>=0) byZone[zone[i]].push(i);
  function shuffle(a){
    for(let k=a.length-1;k>0;k--){const j=(rng()* (k+1))|0; const t=a[k]; a[k]=a[j]; a[j]=t;}
  }
  for(let z=0;z<ZONES.length;z++){
    const idx=byZone[z]; shuffle(idx);
    const nVac=Math.round((ZV.rates[z]||0.109)*idx.length);
    const nNeg=Math.min(nVac, Math.round((ZV.negFrac[z]||0.45)*nVac));
    for(let k=0;k<idx.length;k++){
      const i=idx[k];
      const Z=ZONES[z];
      let d=1e9; for(const[sx,sy]of STATIONS){const dx=(i%W)-sx,dy=(i/W|0)-sy;d=Math.min(d,Math.hypot(dx,dy));}
      const stBonus=Math.max(0,0.28-0.045*d);
      loc[i]=Z.price*(0.85+0.30*rng())+stBonus;
      q[i]=0.45+0.5*rng();
      oAge[i]=35+45*rng()+Z.ageS;
      oRemote[i]=rng()<0.12?1:0; oCo[i]=1;
      if(k<nVac){
        if(k<nNeg) st[i]=S_NEG;
        else st[i]=rng()<0.45?S_SALE:S_LIST;
      }else{
        st[i]=rng()<0.88?S_OCC:S_RENT;
      }
    }
  }
  for(let i=0;i<N;i++) if(zone[i]<0) st[i]=S_DEMO;
  const attach=new Float32Array(N); for(let i=0;i<N;i++)attach[i]=5+8*rng();
  return{seed,policy,rng,loc,q,st,oAge,oRemote,oCo,attach,year:0,
    negYears:new Float32Array(N), hist:{vac:[],neg:[],clu:[]}};
}

/* ---------- 近傍空き家率 ---------- */
function neighborVac(w){
  const nv=new Float32Array(N), vac=i=>w.st[i]>=S_SALE&&w.st[i]<=S_NEG;
  for(let y=0;y<H;y++)for(let x=0;x<W;x++){
    let c=0,v=0;
    for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){
      if(!dx&&!dy)continue;
      const nx=x+dx,ny=y+dy;
      if(nx<0||ny<0||nx>=W||ny>=H)continue;
      const j=ny*W+nx; if(zone[j]<0||w.st[j]===S_DEMO)continue;
      c++; if(vac(j))v++;
    }
    nv[y*W+x]=c?v/c:0;
  }
  return nv;
}

/* ---------- 1年進める ---------- */
function step(w){
  const r=w.rng, pol=w.policy, nv=neighborVac(w);
  const price=i=>1800*w.loc[i]*w.q[i]*Math.max(0.35,1-P.priceVacElast*nv[i]); // 万円
  // 成約見込み（年あたり）：立地×品質が高く、近隣空き家が少ないほど埋まりやすい
  const zDem=ZONES.map(Z=>Math.min(1.6,Math.max(0.60,1+18*Z.mig+0.35*(Z.inc-1))));
  const match=i=>Math.min(0.9,Math.max(0.08,
    (0.22+0.95*w.loc[i]*w.q[i]-0.30*nv[i])*zDem[zone[i]]));

  for(let i=0;i<N;i++){
    if(zone[i]<0||w.st[i]===S_DEMO)continue;

    // 所有者の加齢・死亡 → 相続
    w.oAge[i]+=1;
    const pDeath=1/(1+Math.exp(-P.deathK*(w.oAge[i]-P.deathMid)));
    if(r()<pDeath){
      w.oAge[i]=Math.max(38,w.oAge[i]-31+8*(r()-0.5));
      w.oRemote[i]=r()<0.55?1:0;
      const u=r(); w.oCo[i]=u<0.5?1:(u<0.82?2:3); w.attach[i]=40+45*r();
      if(w.st[i]===S_OCC)w.st[i]=S_NEG;            // 居住者＝所有者だった住戸は空く
    }
    // 転出・退去
    if(w.st[i]===S_OCC&&r()<P.moveOut*Math.min(1.25,Math.max(0.4,1-30*ZONES[zone[i]].mig)))w.st[i]=S_NEG;
    if(w.st[i]===S_RENT&&r()<P.tenantLeave)w.st[i]=S_NEG;

    // 空き家所有者の意思決定（共有名義・遠隔居住は意思決定頻度を下げる）
    if(w.st[i]>=S_SALE&&w.st[i]<=S_NEG){
      w.q[i]=Math.max(0.05,w.q[i]-(w.st[i]===S_NEG?P.vacDecay:P.vacDecay*0.4));
      w.negYears[i]+=(w.st[i]===S_NEG)?1:0;
      const pDecide=Math.min(0.95,(1/w.oCo[i])*(w.oRemote[i]?0.45:1)*(1+0.25*pol.tax));
      if(r()<pDecide){
        const pv=price(i), m=match(i);
        // 何もしない場合の10年コスト：保有費＋空き家課税＋劣化による資産減価
        const holdTax=(P.holdCost+pol.tax/100*pv)*P.horizon;
        const fade=Math.max(0.25,1-0.05*w.negYears[i]);
        const uNeg=-holdTax-pv*P.vacDecay*P.horizon*0.5+w.attach[i]*fade;
        // 行動には意思決定コスト（共有名義・遠隔で増加）
        const eff=P.effort*w.oCo[i]*(w.oRemote[i]?1.5:1)*Math.max(0.25,1-0.07*w.negYears[i]);
        // 売却：成約すれば保有コスト回避＋流動性選好。成約見込みで割引
        const uSell=m*(holdTax+P.liqPref*pv)-P.hassle-eff;
        // 賃貸：純収益×成約見込み − 品質次第の改修費
        const uRent=m*(P.rentYield*pv-P.upkeep)*P.horizon
                    -P.renovCost*(1-w.q[i])*2.0-eff;
        // 解体：更地価値の一部＋保有コスト回避 − (解体費−補助金) − 特例喪失
        const uDemo=pv*P.landFrac+holdTax*0.6-(P.demoBase-pol.sub)
                    -P.taxRelief*P.horizon-eff;
        const us=[["sale",uSell],["rent",uRent],["demo",uDemo],["neg",uNeg]];
        let best=null,bv=-1e18;
        for(const[k,v]of us){const vv=v+P.choiceNoise*(r()-0.5)*2;if(vv>bv){bv=vv;best=k;}}
        if(best==="sale")w.st[i]=S_SALE;
        else if(best==="rent")w.st[i]=S_LIST;
        else if(best==="demo")w.st[i]=S_DEMO;
        else w.st[i]=S_NEG;
      }
    }
  }

  // マッチング：売出・募集中の各物件が成約見込みに応じて埋まる
  for(let i=0;i<N;i++){
    if(zone[i]<0)continue;
    if(w.st[i]===S_SALE||w.st[i]===S_LIST){
      if(r()<match(i)){
        if(w.st[i]===S_SALE){w.st[i]=S_OCC;w.oAge[i]=32+18*r();w.oRemote[i]=0;w.oCo[i]=1;w.q[i]=Math.min(1,w.q[i]+0.15);}
        else{w.st[i]=S_RENT;w.q[i]=Math.min(1,w.q[i]+0.08);}
      }
    }
  }

  // 集計
  let occ=0,vac=0,neg=0,tot=0;
  for(let i=0;i<N;i++){if(zone[i]<0||w.st[i]===S_DEMO)continue;tot++;
    if(w.st[i]>=S_SALE&&w.st[i]<=S_NEG){vac++;if(w.st[i]===S_NEG)neg++;}else occ++;}
  const nv2=neighborVac(w);
  let s=0,c=0;for(let i=0;i<N;i++)if(zone[i]>=0&&w.st[i]>=S_SALE&&w.st[i]<=S_NEG){s+=nv2[i];c++;}
  const clu=(c&&vac/tot>0)?(s/c)/(vac/tot):0;
  w.hist.vac.push(vac/tot);w.hist.neg.push(neg/tot);w.hist.clu.push(clu);
  w.year++;
}

  return {
    mulberry32, makeWorld, neighborVac, step,
    W, H, N, ZONES, zone,
    S_OCC, S_RENT, S_SALE, S_LIST, S_NEG, S_DEMO,
    COLORS, STATIONS, P,
  };
});
